steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "europe-southwest1-docker.pkg.dev/tienda-microservices-452308/image-registry/auth-ms",
        "-f",
        "dockerfile.prod",
        "--platform=linux/amd64",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "europe-southwest1-docker.pkg.dev/tienda-microservices-452308/image-registry/auth-ms",
      ]
options:
  logging: CLOUD_LOGGING_ONLY