# Dependencias
FROM node:23.8.0-alpine3.21 AS deps

WORKDIR /usr/src/app

COPY package*.json ./
COPY package-lock.json ./

RUN npm install




# Builder - Construye la aplicación
FROM node:23.8.0-alpine3.21 AS build

WORKDIR /usr/src/app

#Copiar de deps, los módulos de node
COPY --from=deps /usr/src/app/node_modules ./node_modules

#Copiar el código fuente de la aplicación
COPY . .

#RUN npm run test
RUN npm run build

RUN npm ci -f --only=production && npm cache clean --force

RUN npx prisma generate



#Crear la imagen final de Docker

FROM node:23.8.0-alpine3.21 AS prod

COPY --from=build /usr/src/app/node_modules ./node_modules

#Copiar la carpeta de DIST
COPY --from=build /usr/src/app/dist ./dist

ENV NODE_ENV=production

USER node

EXPOSE 3000

CMD [ "node", "dist/main" ]